---
- name: Add ROS repository apt-key
  apt_key:
    url: "{{ ros_apt_key }}"
    state: present

- name: Add ROS repository
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
    filename: ros-latest

# - name: ROS Dep Setup

# - name: ROS Dep Update

- name: Install desired ROS package
  apt:
    pkg: "ros-{{ ros_release }}-{{ ros_package }}"
    state: latest

- name: Update existing ROS packages
  apt:
    pkg: ros-{{ ros_release }}-* python-wstool python-catkin-* python-bloom
    only_upgrade: true